"""
Complaint-status lookups for the RAG assistant.

SECURITY DESIGN DECISION, stated explicitly: a citizen's own complaint
data is NEVER put into an LLM prompt or generated by the LLM. Personal
data is looked up deterministically from the database and formatted with
plain string logic, with authorization checked in code before the DB
query even runs. Relying on prompt instructions ("don't reveal other
users' complaints") to enforce access control would be unsafe - a model
can be tricked by prompt injection, and even without that, generation is
probabilistic. Authorization has to happen in code, not in a prompt.

This module is intentionally DB-agnostic (pure functions on dicts) so it
can be unit-tested without a database - app.py is responsible for
fetching the complaint row and passing it in.
"""

import re
from typing import Optional

_COMPLAINT_ID_PATTERN = re.compile(r"#\s*(\d+)|complaint\D{0,15}?(\d+)", re.IGNORECASE)


def extract_complaint_id(text: str) -> Optional[int]:
    """Looks for a complaint id in phrasing like '#12', 'complaint 12',
    'complaint id 12', 'complaint number 12'. Returns None if no number
    is found - callers should fall back to normal knowledge-base RAG."""
    if not text:
        return None
    match = _COMPLAINT_ID_PATTERN.search(text)
    if not match:
        return None
    number = match.group(1) or match.group(2)
    try:
        return int(number)
    except (TypeError, ValueError):
        return None


def is_authorized(complaint: dict, user_id: int, user_role: str) -> bool:
    """Officers and admins can look up any complaint (same access they
    already have via /all-complaints); citizens only their own."""
    if user_role in ("officer", "admin"):
        return True
    return complaint.get("user_id") == user_id


def format_complaint_answer(complaint: dict, resolution_estimate: Optional[dict] = None) -> str:
    """Deterministic, template-based - NOT generated by an LLM. Every
    fact here comes directly from the DB row passed in."""
    lines = [
        f"Complaint #{complaint['id']} ({complaint['category']}): status is currently \"{complaint['status']}\".",
        f"Priority: {complaint.get('priority', 'not set')}.",
    ]
    if complaint.get("created_at"):
        lines.append(f"Submitted on: {complaint['created_at']}.")

    if resolution_estimate and resolution_estimate.get("available"):
        note = " (based on a bootstrap model, treat as illustrative)" if resolution_estimate.get("low_confidence") else ""
        lines.append(
            f"AI-estimated resolution time: ~{resolution_estimate['predicted_days']} days{note}. "
            "This is an estimate, not a guaranteed deadline."
        )

    return " ".join(lines)


def not_found_message() -> str:
    """Deliberately the SAME message whether the complaint doesn't exist
    or exists but belongs to someone else - confirming which would leak
    information about other citizens' complaint IDs to an unauthorized
    requester."""
    return "I couldn't find that complaint under your account."
